version: "3.7"

services:
  landing-page:
    build: .
    image: escola-jerbs-landing:latest
    container_name: escola-jerbs-app
    restart: always
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

    # -----------------------------------------------------
    # INÍCIO DA ALTERAÇÃO
    # -----------------------------------------------------
    # Abrimos a porta 3000 diretamente para teste via IP
    ports:
      - "3000:3000"
    # -----------------------------------------------------
    # FIM DA ALTERAÇÃO
    # -----------------------------------------------------

    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.escola-jerbs.rule=Host(`escolajerbs.com.br`, `www.escolajerbs.com.br`)"
        - "traefik.http.routers.escola-jerbs.entrypoints=websecure"
        - "traefik.http.routers.escola-jerbs.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.escola-jerbs.loadbalancer.server.port=3000"

networks:
  network_public:
    external: true
