name: Build and Push to Docker Hub

on:
  push:
    branches:
      - v2-deploy # Troque para 'v2-deploy' se for a branch que você usa

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # AQUI ESTÁ A MÁGICA: Apontando para o seu repositório exato
          tags: systemdaan/escola-jerbs:latest
          cache-from: type=gha
          cache-to: type=inline
